HTTP 201 Created
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Feature-Policy: payment 'self'
X-Recruiting: /#/jobs
Location: /api/Users/45
Content-Type: application/json; charset=utf-8
Content-Length: 320
ETag: W/"140-m9aBMvbnJkFr/+aoglU88btYQpk"
Vary: Accept-Encoding
Date: Sat, 05 Sep 2026 19:52:06 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"status":"success","data":{"username":"","role":"customer","deluxeToken":"","lastLoginIp":"0.0.0.0","profileImage":"/assets/public/images/uploads/default.svg","isActive":true,"id":45,"email":"resetpwd-71e32870fe@lab.local","updatedAt":"2026-09-05T19:52:05.981Z","createdAt":"2026-09-05T19:52:05.981Z","deletedAt":null}}