POST http://127.0.0.1:3000/api/SecurityAnswers/
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjo0NSwidXNlcm5hbWUiOiIiLCJlbWFpbCI6InJlc2V0cHdkLTcxZTMyODcwZmVAbGFiLmxvY2FsIiwicGFzc3dvcmQiOiJlZTUxMjYxZDgzYzQwYTJlNmVjMjVkYzBlYTUwYmY0YiIsInJvbGUiOiJjdXN0b21lciIsImRlbHV4ZVRva2VuIjoiIiwibGFzdExvZ2luSXAiOiIwLjAuMC4wIiwicHJvZmlsZUltYWdlIjoiL2Fzc2V0cy9wdWJsaWMvaW1hZ2VzL3VwbG9hZHMvZGVmYXVsdC5zdmciLCJ0b3RwU2VjcmV0IjoiIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjYtMDktMDUgMTk6NTI6MDUuOTgxICswMDowMCIsInVwZGF0ZWRBdCI6IjIwMjYtMDktMDUgMTk6NTI6MDUuOTgxICswMDowMCIsImRlbGV0ZWRBdCI6bnVsbH0sImJpZCI6MjUsImlhdCI6MTc4ODYzNzkyNn0.iNfjDzfMFDGj6pUTYIoBDyWw3vgmaUgSoQmcopkWfz8Nx4GYLHcft3_7xDn_hLrMXAWSfxGlyJOFMsxUlU_UdpFkc0gAPKdsPOwNy9xu0n6wkClWaiRYXCgvGZt7eaM83aUF3kChczRGMIyxff0CwodhQqYIXfc2SlB774lsgKo
Content-Length: 57
Content-Type: application/json

{"SecurityQuestionId": 1, "answer": "John", "UserId": 45}