POST http://127.0.0.1:3000/api/Users
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 180
Content-Type: application/json

{"email": "bruteforce-837d92427c@lab.local", "password": "SenhaCorreta#9", "passwordRepeat": "SenhaCorreta#9", "securityQuestion": {"id": 1}, "securityAnswer": "resposta-de-teste"}