POST http://127.0.0.1:3000/api/Users
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 170
Content-Type: application/json

{"email": "idor-01ea4d1571@lab.local", "password": "SenhaForte#1", "passwordRepeat": "SenhaForte#1", "securityQuestion": {"id": 1}, "securityAnswer": "resposta-de-teste"}