POST http://127.0.0.1:3000/rest/user/login
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 66
Content-Type: application/json

{"email": "idor-e7de49555a@lab.local", "password": "OutraSenha#2"}