POST http://127.0.0.1:3000/api/BasketItems/
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjo0MiwidXNlcm5hbWUiOiIiLCJlbWFpbCI6Imlkb3ItMDFlYTRkMTU3MUBsYWIubG9jYWwiLCJwYXNzd29yZCI6ImZlYzgzNDM4YTEwNGViNTIzNDczYjNlMGZmZjdiNWFhIiwicm9sZSI6ImN1c3RvbWVyIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0LnN2ZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wOS0wNSAxOTo1MjowNC42NzYgKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyNi0wOS0wNSAxOTo1MjowNC42NzYgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiYmlkIjoyMiwiaWF0IjoxNzg4NjM3OTI1fQ.veStp4_rgvRabxC7lo6HScTI139JjvTicY8V82uKZxSIkxU94NGYFQxJRmKo4T_gOgdbPMkA32xt-RZkI-cHcRxSIibbnnt9QlgMBXX8Na0E6RN5yB_b0xT-PRIPD_3OTMTDaqt_WRGWqfcNCRKLtNSB9FPnvVR9jYtLF_L_vBs
Content-Length: 49
Content-Type: application/json

{"ProductId": 1, "BasketId": "22", "quantity": 2}