GET http://127.0.0.1:3000/rest/basket/22
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjo0MywidXNlcm5hbWUiOiIiLCJlbWFpbCI6Imlkb3ItZTdkZTQ5NTU1YUBsYWIubG9jYWwiLCJwYXNzd29yZCI6IjFjNDkzNDIzZGFlMjJjZTIyYjUyMmFhYzg5ZDYwZTBhIiwicm9sZSI6ImN1c3RvbWVyIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0LnN2ZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wOS0wNSAxOTo1MjowNC43NjcgKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyNi0wOS0wNSAxOTo1MjowNC43NjcgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiYmlkIjoyMywiaWF0IjoxNzg4NjM3OTI1fQ.dK9k9unn-xiJo2dcSqZHpFL3Ft6OPwAyVFoNupaSGVir6kHVVgwwhiZGVM-OllbWnM7w_ga6LXeSXqGQ5brPJ494rqvVLndGh9o6kv7ukkyuIwezsM38MHmQGAr2AM4RMGDYNzsibQ3o2H-eB3vNaDDgGnghlGZG3y0JoB9zvFs
